export const stateKey = {
    app: "app",
    users: "users",
    roles: "roles",
    class: "class",
    levels: "levels",
    students: "students",
    activities: "activities",
    facilities: "facilities",
    checkin: "checkin",
    bookings: "bookings",
    counsels: "counsels",
    support_strategies: "support_strategies",
    questions: "questions",
};
